version: '3.8'
services:
  app:
    build: .
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
      - DB_PORT=5432
      - PORT=3000
      - WHITELISTED_ORIGIN=http://localhost:8081,http://localhost:5437