exports.CLIENT_CODE = {
  SUCCESS_CREATED: 'SUCCESS_CREATED',
  FAILED_CREATED: 'FAILED_CREATED',
  SUCCESS_UPDATED: 'SUCCESS_UPDATED',
  FAILED_UPDATED: 'FAILED_UPDATED',
  SUCCESS_FETCH: 'SUCCESS_FETCH',
  FAILED_FETCH: 'FAILED_FETCH',
  SUCCESS_DELETED: 'SUCCESS_DELETED',
  FAILED_DELETED: 'FAILED_DELETED',
};

exports.VERSION_API = '1.0.0';

exports.VERSION_API_DATE = '01/10/2023';
