exports.CLIENT_CODE = {
  SUCCESS_CREATED: 'SUCCESS_CREATED',
  FAILED_CREATED: 'FAILED_CREATED',
  SUCCESS_UPDATED: 'SUCCESS_UPDATED',
  FAILED_UPDATED: 'FAILED_UPDATED',
  SUCCESS_FETCH: 'SUCCESS_FETCH',
  FAILED_FETCH: 'FAILED_FETCH',
  SUCCESS_DELETED: 'SUCCESS_DELETED',
  FAILED_DELETED: 'FAILED_DELETED',
};

exports.VERSION_API = '1.0.0';

exports.VERSION_API_DATE = '01/10/2023';

exports.CHART_TYPE = {
  GROUPING_BY_SENTIMENT: 'GROUPING_BY_SENTIMENT',
  COUNT_TRENDING_TOPIC_APPEARANCES: 'COUNT_TRENDING_TOPIC_APPEARANCES',
  COUNT_SCRAPE_SENTIMENT_PER_DAY: 'COUNT_SCRAPE_SENTIMENT_PER_DAY',
}
