name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep 'tag_name' | cut -d\" -f4)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and Run Services
        run: |
          docker-compose up --build -d

      # - name: Run Tests
      #   run: docker-compose exec app npm test

      - name: Push Docker Image to GitHub Container Registry
        run: |
          docker-compose build app
          docker tag trendz-api ghcr.io/${{ github.repository }}/trendz-api:latest
          docker push ghcr.io/${{ github.repository }}/trendz-api:latest

      - name: Deploy to Production Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          echo "DB_NAME=$DB_NAME" >> .env
          echo "DB_HOST=$DB_HOST" >> .env
          echo "DB_USERNAME=$DB_USERNAME" >> .env
          echo "DB_PASSWORD=$DB_PASSWORD" >> .env
          echo "$SSH_PRIVATE_KEY" > trendz-api-key
          chmod 600 trendz-api-key
          ssh -i private_key -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "cd /path/to/your/app && docker-compose pull && docker-compose up -d"
          rm private_key